config/routes.rb
Example::Application.routes.draw do

  resources :groups

  root :to => "static_pages#home"
  match '/about', :to=> 'static_pages#about'
  match '/help', :to=> 'static_pages#help'
  match '/contact', :to=> 'static_pages#contact'  
  
  match '/signup',  :to=> 'users#new'  
  match '/signin',  :to=> 'sessions#new'
  match '/signout', :to=> 'sessions#destroy', :via=> :delete
  
  
  get "microposts/new"

  resources :photos
  resources :users
  resources :sessions, :only=> [:new, :create, :destroy]
  resources :microposts, :only=> [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost  = current_user.microposts.build if signed_in?
      @feed_items = current_user.feed.paginate(:page=> params[:page])
    end
  end
  def help
  end
  
  def about
  end
 
  def contact
  end  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="center">
<h1>About</h1>
<img src="http://www.mat.ucsb.edu/g.legrady/glWeb/Projects/jbc/images/001river.jpg" class="center"></img>
</div>
<br>
<p>In 1972 I visited Fort George, a Cree village on the east side of James Bay in northern sub-arctic Quebec, upon the invitation of the Quebec Metis Association to document the half-breed inhabitants who were fighting to receive goverment recognition of their Indian status. The following summer, my brother and I returned with two other photographers to document the way of life of the James Bay Eastern Cree Indians inhabiting the four villages alongside James Bay. The large geographic area was used by the people since prehistory as their hunting and trapping lands. The documentary was produced in response to the political circumstances of the Cree taking legal action against the James Bay Hydro Electric Corporation, whose project consisted in creating one of North America’s largest hydro-electric dam systems blocking the main rivers in the area. The flooding resulted in major ecological imbalances not to mention invasion and destruction of Indian land.
</p>
<p>The documentary projects' short term use value was to provide a visual record of this traditional culture for the urban Montreal public, thereby rallying support to the indigenous cause. The James Bay project signaled the development of an hitherto inaccessible area, a true cultural invasion through the penetrtation of a white labor force, the introduction of television and the building of a freeway connecting the sub-Artic to the southern industrial centers. This photo documentary's inherent long term goal was to create an ethnographic historical record of the indigenous lifestyles before its imminent transition to global culture. The socio-cultural environment has in fact significantly changed since the time of my original documentation in 1973.</p>
<p>The resultant images were used in various ways. In Rupert's House it became part of the elementary classroom visual material. In the village's meeting hall were displayed portraits of the elders. Portfolios were published in Akwesasne Notes , a journal published by the Mohawk nation, OVO magazine, a Quebec journal with a documentary focus and a Parisian journal focusing on social Medicare, amongst others. This photographic archive is the history of a community at a particular moment in time and my personal interaction with them. With 30 years’ having gone by, the James Bay communities have changed and this material may be ready for historical reevaluation, to be annotated by the educators and cultural workers of the James Bay communities. </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>    
  </div>  
<% else %>
  <div class="center">
    <h1>The James Bay Project</h1>

	<img src="http://www.mat.ucsb.edu/g.legrady/glWeb/Projects/jbc/images/007guys.jpg"></img>
	<br>
    <%= #link_to "Sign up now!", signup_path, :class=> "btn btn-large btn-primary"
    	link_to "Sign up now!", signup_path, :class=> "btn btn-large btn-primary"  
    %>
    <%= link_to "Sign in", signin_path, :class=> "btn btn-large btn-primary" %>
  </div>

  <!--<%= link_to image_tag("rails.png", :alt=> "Rails"), 'http://rubyonrails.org/' %>-->
<% end %> 