config/routes.rb
Example::Application.routes.draw do

  resources :groups

  root :to => "static_pages#home"
  match '/about', :to=> 'static_pages#about'
  match '/help', :to=> 'static_pages#help'
  match '/contact', :to=> 'static_pages#contact'  
  
  match '/signup',  :to=> 'users#new'  
  match '/signin',  :to=> 'sessions#new'
  match '/signout', :to=> 'sessions#destroy', :via=> :delete
  
  
  get "microposts/new"

  resources :photos
  resources :users
  resources :sessions, :only=> [:new, :create, :destroy]
  resources :microposts, :only=> [:create, :destroy]

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :photographer, :collection, :format, :size, :location, :coordinates
  attr_accessible :title, :creeSyllables, :description, :longDescription, :subjects, :imageType
  attr_accessible :aestheticRating, :ethnographicRating, :communityRating, :dateTaken, :url
    
  belongs_to :user
  has_many :microposts
  has_and_belongs_to_many :groups
  validates :title, :presence=>:true
  validates :url, :presence=>:true
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  #like private with exceptions
  before_filter :signed_in_user
  before_filter :correct_user,   :only=> :destroy
  
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])
    @microposts = @photo.microposts.paginate(:page=> params[:page]) #paginate is smart and reaches into the microposts table
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, :notice => 'Photo was successfully created.' }
        format.json { render :json => @photo, :status => :created, :location => @photo }
      else
        format.html { render :action => "new" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, :notice => 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Title" %><br />
    <%= f.text_field :title %>
  </div>
    <div class="field">
    <%= f.label "URL" %><br />
    <%= f.text_field :url %>
  </div>
    <div class="field">
    <%= f.label "Photographer" %><br />
    <%= f.text_field :photographer %>
  </div>
    <div class="field">
    <%= f.label "Collection" %><br />
    <%= f.text_field :collection %>
  </div>
    <div class="field">
    <%= f.label "Format" %><br />
    <%= f.text_field :format %>
  </div>
    <div class="field">
    <%= f.label "Size" %><br />
    <%= f.text_field :size %>
  </div>
      <div class="field">
    <%= f.label "Location" %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label "Coordinates" %><br />
    <%= f.text_field :coordinates %>
  </div>
      <div class="field">
    <%= f.label "Cree Syllables" %><br />
    <%= f.text_field :creeSyllables %>
  </div>
        <div class="field">
    <%= f.label "Description" %><br />
    <%= f.text_field :description %>
  </div>
      <div class="field">
    <%= f.label "Detailed Description" %><br />
    <%= f.text_field :longDescription %>
  </div>
      <div class="field">
    <%= f.label "Subjects" %><br />
    <%= f.text_field :subjects %>
  </div>
        <div class="field">
    <%= f.label "Image Type" %><br />
    <%= f.text_field :imageType%>
  </div>
        <div class="field">
    <%= f.label "Aesthetic Rating" %><br />
    <%= f.number_field :aestheticRating %>
  </div>
        <div class="field">
    <%= f.label "Ethnographic Rating" %><br />
    <%= f.number_field :ethnographicRating %>
  </div>
          <div class="field">
    <%= f.label "Community Rating" %><br />
    <%= f.number_field :communityRating %>
  </div>
  <div class="field">
    <%= f.label "Date Taken (yyyy-mm-dd)" %><br />
    <%= f.date_select(:dateTaken, :include_blank=> true, :start_year=> 1900, :end_year=> Date.today.year, :default=> Date.new(1970,01,01)) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.title %></td>
    <td><%= photo.user_id %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<% provide(:title, @photo.title) %>
<div class="row">
  <aside class="span4">
<p>
  <b>Title:</b>
  <%= @photo.title %>
</p>
<p>
  <b>Photographer:</b>
  <%= @photo.photographer %>
</p>
<p>
  <b>Collection:</b>
  <%= @photo.collection %>
</p>

<p>
  <b>Format:</b>
  <%= @photo.format %>
</p>
<p>
  <b>Size:</b>
  <%= @photo.size %>
</p>
<p>
  <b>Location:</b>
  <%= @photo.location %>
</p>
<p>
  <b>Coordinates:</b>
  <%= @photo.coordinates %>
</p>
<p>
  <b>Cree Syllables:</b>
  <%= @photo.creeSyllables %>
</p>
<p>
  <b>Description:</b>
  <%= @photo.description %>
</p>
<p>
  <b>Detailed Description:</b>
  <%= @photo.longDescription %>
</p>
<p>
  <b>Subjects:</b>
  <%= @photo.subjects %>
</p>
<p>
  <b>Image Type:</b>
  <%= @photo.imageType %>
</p>
<p>
  <b>Aesthetic Rating:</b>
  <%= @photo.aestheticRating %>
</p>
<p>
  <b>Ethnographic Rating:</b>
  <%= @photo.ethnographicRating %>
</p>
<p>
  <b>Community Rating:</b>
  <%= @photo.communityRating %>
</p>
<p>
  <b>Date Taken:</b>
  <%= @photo.dateTaken %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>
  </aside>
  <div class="span8">
  	<img src="<%=@photo.url%>"></img>
    <% if @photo.microposts.any? %>
      <h3>Microposts (<%= @photo.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>  
</div>